### ISSUE TITLE
When will the actual code be available?

### ISSUE THREAD

**Issue by silva-vinicius** [wwliu555/IRGNN_TNNLS_2021#1]
Hi @wwliu555, I have read your paper and would like to reproduce your results, however, only the README.md file is available in this repo and I would like to know when (or if) you plan to make the code available to the community.
Thanks.

**Comment by wwliu555** [comment]
Working on it, shall be available by the end of this month, hopefully:)

**Comment by silva-vinicius** [comment]
Code is available.
