### ISSUE TITLE
Requirements.txt file

### ISSUE THREAD

**Issue by silva-vinicius** [wwliu555/IRGNN_TNNLS_2021#2]
Hi, I'm trying to execute your code, but I'm having issues with dependencies. Can you please post your requirements.txt (`python -m pip freeze > requirements.txt`) file specifying which version of every library you are using?

Thank you

**Comment by wwliu555** [comment]
Here are what I got:)

certifi==2019.6.16
cffi==1.12.3
cycler==0.10.0
decorator==4.4.0
easydict==1.9
gensim==3.8.3
h5py==2.9.0
imagecodecs==2020.2.18
imageio==2.8.0
isodate==0.6.0
joblib==0.13.2
k-gnn==0.0.0
kiwisolver==1.2.0
matplotlib==3.2.1
mkl-fft==1.0.12
mkl-random==1.0.2
networkx==2.3
numpy==1.16.4
olefile==0.46
pandas==0.25.1
Pillow==6.0.0
plyfile==0.7
protobuf==3.9.1
pycairo==1.18.1
pycparser==2.19
pyparsing==2.4.0
python-dateutil==2.8.0
python-rapidjson==0.8.0
pytz==2019.2
PyWavelets==1.1.1
PyYAML==5.1.2
rdflib==4.2.2
scikit-image==0.17.2
scikit-learn==0.21.2
scipy==1.3.0
six==1.12.0
smart-open==4.0.1
tensorboardX==1.8
texttable==1.6.3
tifffile==2020.5.11
torch==1.1.0
torch-cluster==1.4.2
torch-geometric==1.3.0
torch-scatter==1.3.1
torch-sparse==0.4.0
torch-spline-conv==1.1.0
torchvision==0.3.0
tqdm==4.35.0
